# Add new comment

POST http://localhost:3000/api/comments/ HTTP/1.1
Content-Type: application/json

{
  "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi venenatis egestas tortor sit amet iaculis.",
  "postId": "3"
}

###

# Delete comment

DELETE http://localhost:3000/api/comments/d5d039ab-aefb-4543-9445-347982821f6c HTTP/1.1

###

# List comments for a post

GET http://localhost:3000/api/comments/ HTTP/1.1

###
