# Create new post

POST http://localhost:6000/api/posts HTTP/1.1
Content-Type: application/json

{
  "type": "photo",
  "tags": ["ShakesPeare", "cite", "author"],
  "videoURL": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi venenatis egestas tortor sit amet iaculis.",
  "text": "fdljfdlfkjdfld",
  "photo": "photo"
}

###

#Show post details

GET http://localhost:6000/api/posts/751e27e3-22ba-4a09-afba-945ada7057d2 HTTP/1.1

###

#Update post data

PATCH http://localhost:6000/api/posts/751e27e3-22ba-4a09-afba-945ada7057d2 HTTP/1.1
Content-Type: application/json

{
  "photo": "Jane Ostin"
}

###

#Delete post

DELETE http://localhost:6000/api/posts/dfae4f94-8d19-4572-a105-f62740c44bd1 HTTP/1.1

###

#Repost post

POST http://localhost:6000/api/posts/repost/1f8eb4c9-e011-4a45-ae67-30d17c87898f HTTP/1.1

###
