# Create new post

POST http://localhost:7000/api/posts HTTP/1.1
Content-Type: application/json

{
  "type": "text",
  "tags": ["Mark Twain", "writer", "novel"],
  "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi venenatis egestas tortor sit amet iaculis.",
  "announce": "this is post announce",
  "title": "Lorem ipsum dolor sit amet"
}

###

#Show post details

GET http://localhost:7000/api/posts/044cec4f-bc7c-4f76-b45b-010f76270401 HTTP/1.1

###

#Update post data

PATCH http://localhost:7000/api/posts/e77dfe34-e3b0-4465-890c-1328b0d91d43 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWIzYTczMTliNDhiNjZlMjM1ZWJkNzAiLCJlbWFpbCI6Im5ldzJAdXNlci5jb20iLCJmaXJzdE5hbWUiOiJBbGV4IiwibGFzdE5hbWUiOiJCb2Noa2luIiwiaWF0IjoxNzA2Mjc1OTYyLCJleHAiOjE3MDg4Njc5NjJ9.NKmxS5VGH4YgSYHDT4a44MfNJmkBUG0MV13IddnDiXs

{
  "announce": "Новый анонс"
}

###

#Delete post

DELETE http://localhost:7000/api/posts/044cec4f-bc7c-4f76-b45b-010f76270401 HTTP/1.1

###

#Repost post

POST http://localhost:7000/api/posts/repost/1f8eb4c9-e011-4a45-ae67-30d17c87898f HTTP/1.1

###

# Get list of posts

GET http://localhost:7000/api/posts?type=photo HTTP/1.1

###

# Search posts by title

GET http://localhost:7000/api/posts/search?title=Lorem HTTP/1.1

###

# List user drafts

GET http://localhost:7000/api/posts/drafts HTTP/1.1

###
