# Create new post

POST http://localhost:6000/api/posts HTTP/1.1
Content-Type: application/json

{
  "type": "photo",
  "tags": ["ShakesPeare", "cite", "author"],
  "videoURL": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi venenatis egestas tortor sit amet iaculis.",
  "text": "fdljfdlfkjdfld",
  "photo": "photo"
}

###

#Show post details

GET http://localhost:6000/api/posts/044cec4f-bc7c-4f76-b45b-010f76270401 HTTP/1.1

###

#Update post data

PATCH http://localhost:6000/api/posts/044cec4f-bc7c-4f76-b45b-010f76270401 HTTP/1.1
Content-Type: application/json

{
  "photo": "Jane_Osti.png"
}

###

#Delete post

DELETE http://localhost:6000/api/posts/044cec4f-bc7c-4f76-b45b-010f76270401 HTTP/1.1

###

#Repost post

POST http://localhost:6000/api/posts/repost/1f8eb4c9-e011-4a45-ae67-30d17c87898f HTTP/1.1

###
