# Upload Avatar
POST http://localhost:8000/api/upload/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="800.jpg"
Content-Type: image/jpeg


< ./800.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# Upload Photo
POST http://localhost:8000/api/upload/photo HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="avatar.png"
Content-Type: image/png


< ./avatar.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###



# Get file by ID
GET http://localhost:8000/api/upload/65b37dec4960a65cc0c41dc1 HTTP/1.1

###
