# Register new user
POST http://localhost:5000/api/auth/signin HTTP/1.1
Content-Type: application/json

{
  "email": "new16@user.com",
  "firstname": "Alex",
  "lastname": "Bochkin",
  "password": "123456"
}

###

# Get user by Id
GET http://localhost:5000/api/auth/65a7924e332cda36b5dc87bd HTTP/1.1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5ldzEwQHVzZXIuY29tIiwiZmlyc3ROYW1lIjoiQWxleCIsImxhc3ROYW1lIjoiQm9jaGtpbiIsImlhdCI6MTcwNTQ4MDgwNCwiZXhwIjoxNzA1NDgxMTY0fQ.Vf9duKyTbWzjbSPi8cAbtpPn-xM11mr-OxdYeDjrCNU
###

# Login user
POST http://localhost:5000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "new10@user.com",
  "password": "123456"
}

###
