# Register new user
POST http://localhost:5000/api/auth/signin HTTP/1.1
Content-Type: application/json

{
  "email": "new16@user.com",
  "firstname": "Alex",
  "lastname": "Bochkin",
  "password": "123456",
  "avatar": "picture.jpg"
}

###

# Get user by Id
GET http://localhost:5000/api/auth/65a7924e332cda36b5dc87bd HTTP/1.1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5ldzEwQHVzZXIuY29tIiwiZmlyc3ROYW1lIjoiQWxleCIsImxhc3ROYW1lIjoiQm9jaGtpbiIsImlhdCI6MTcwNTgxODU4OCwiZXhwIjoxNzA4NDEwNTg4fQ.Mn-xVMoIVE5A4qKY3s6jee1zbdQfdW8nm_lBXjV5TYg

###

# Login user
POST http://localhost:5000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "new10@user.com",
  "password": "123456"
}

###

# Get new JWT pair
POST http://localhost:5000/api/auth/refresh HTTP/1.1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5ldzEwQHVzZXIuY29tIiwiZmlyc3ROYW1lIjoiQWxleCIsImxhc3ROYW1lIjoiQm9jaGtpbiIsImlhdCI6MTcwNTgxMzcyMSwiZXhwIjoxNzA1ODE0MDgxfQ.1BfgiY9xxPT4VbKPLLmr376V4A9n85KwyRQ0WaLEfaM

###
